
import "./globals.css";
import Navegation from "@/Components/Navegation";
import Footer from "@/Components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navegation />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
